### ISSUE TITLE
Work Sans in Office 365

### ISSUE THREAD

**Issue by DoreenGerold** [weiweihuanghuang/Work-Sans#62]
My client is using Work Sans as their new corporate font. The main use is on the website, where everything works very well. But also in office applications like Word and Excel. There are real problems here, because the letters and numbers often jump randomly, here is a screen from an Excel spreadsheet.

![work_Sans](https://user-images.githubusercontent.com/87017362/124597046-43780600-de63-11eb-9cab-ca4630175ea0.png)

Is the problem known? Is there a solution? 
If it can't be solved, the client is already considering switching back to Calibri.  Of course, we don't want that. 

Please advise.
Doreen

**Comment by kenmcd** [comment]
A similar issue was reported with the Cascadia Code font and Excel: https://github.com/microsoft/cascadia-code/issues/523 
According to that discussion it may be related to when the words include accented characters.
But that does not appear to be entirely consistent with your image above (2nd row looks OK).
Does Calibri always work?

**Comment by weiweihuanghuang** [comment]
Thanks for the answer @kenmcd, I guess I can't do anything about it unfortunately. Have you seen this @m4rc1e ?

**Comment by DoreenGerold** [comment]
There are no problems with Calibri or other system fonts. The problem does not always appear, but rather randomly. The letters simply jump up from the line without changing the formatting.

**Comment by weiweihuanghuang** [comment]
This should be fixed

**Comment by fquadt** [comment]
This is still an issue in Microsoft Excel, @weiweihuanghuang 
<img width="385" alt="work-sans" src="https://github.com/weiweihuanghuang/Work-Sans/assets/337361/7cd2622f-a473-48c4-a2b1-ba7c29c70896">
What did you do in the end @DoreenGerold 

Greetings
Florian
